spring:
  datasource:
    url: jdbc:mysql://localhost/my_db?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp